name: flutter_starter_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.2
  go_router: ^13.2.0
  equatable: ^2.0.5
  retrofit: ^4.4.1
  dio: ^5.7.0
  built_value: ^8.9.2
  json_annotation: ^4.9.0
  retrofit_generator: ^8.2.1
  built_value_generator: ^8.9.2
  get_it: ^7.7.0
  injectable: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  injectable_generator:  ^2.4.4

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/src/core/theme/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: lib/src/core/theme/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: lib/src/core/theme/fonts/Poppins-Bold.ttf
          weight: 700
